### ISSUE TITLE
Unable to play files on mobile

### ISSUE THREAD

**Issue by zthart** [sgreene570/audiophiler#13]
Neither Chrome or Safari on iOS 11 can play audio and it makes me sad

**Comment by sgreene570** [comment]
Turns out safari on any platform cannot handle audiophiler

**Comment by hearthsinger** [comment]
> you cannot handle my strongest ~potions~ audio hosting, traveler

**Comment by sgreene570** [comment]
Somehow managed to fix this. What even are mimetypes???
