### ISSUE TITLE
no way to disable plug

### ISSUE THREAD

**Issue by sgreene570** [sgreene570/audiophiler#41]
it seems like the template base renders plug no matter what.

**Comment by sgreene570** [comment]
I would like to be able to disable plug through an env variable for audiophiler-dev

**Comment by MoralCode** [comment]
https://github.com/sgreene570/audiophiler/blob/062bfc8cef5e59eaa909171f5e5b718d484cf4a2/audiophiler/templates/main.html#L4

is the config returning a string like i presume it is in https://github.com/sgreene570/audiophiler/blob/062bfc8cef5e59eaa909171f5e5b718d484cf4a2/audiophiler/templates/base.html#L83 ?

**Comment by sgreene570** [comment]
Ah yep theres the issue. Cast that lad!

**Comment by MoralCode** [comment]
or just check if it equals "true"/"True"
